# Generated by Django 5.2.17 on 2026-09-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_category_id_alter_fruit_id_alter_member_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='VehicleLog',
        ),
    ]
